### ISSUE TITLE
change structure of indexes

### ISSUE THREAD

**Issue by deezus-net** [deezus-net/dac#1]
## current:
```
indexes:
  [indexName]:
    columns:
      [columnName]: asc
```
## after:
```
indexes:
  - name: [columnName]    # optional, can be null
    columns:
      [columnName]: asc
```
